import image from "../assets/Rectangle 48.png";

export const CaseStudydata = [
  {
    id: 1,
    date: "Lorem ipsum - 19 Aug 2023",
    title: "A Relentless Pursuit of Perfection In Website Design",
    desc: "I began to notice that there was a sharp contrast between well made....",
    imgUrl: image,
    keywords: ["Design", "Design", "Research", "Research", "Research"],
  },
  {
    id: 2,
    date: "Lorem ipsum - 19 Aug 2023",
    title: "A Relentless Pursuit of Perfection In Website Design",
    desc: "I began to notice that there was a sharp contrast between well made....",
    imgUrl: image,
    keywords: ["Design", "Design", "Research", "Research", "Research"],
  },
  {
    id: 3,
    date: "Lorem ipsum - 19 Aug 2023",
    title: "A Relentless Pursuit of Perfection In Website Design",
    desc: "I began to notice that there was a sharp contrast between well made....",
    imgUrl: image,
    keywords: ["Design", "Design", "Research", "Research", "Research"],
  },
];

export const TeamMembersKeyword = [
  "All",
  "AI",
  "artificial intelligence",
  "B2B",
  "Broker",
  "business intelligence",
  "ChatGPT",
  "CMS",
  "Compliance",
  "Crypto",
  "data mining",
  "device",
  "DIY",
  "EdTech",
  "Education",
  "Energy",
  "FCPA",
  "Fintech",
  "food",
  "Green Energy",
  "hardware",
  "health",
  "healthcare",
  "Insurance",
  "internet",
  "IOT",
  "Lending",
  "Live",
  "LMS",
  "Loan",
  "Logistics",
  "machine learning",
  "Management Consulting",
  "Marketplace",
  "MLS",
  "MVP",
  "No Code",
  "OpenAI",
  "Politics",
  "Real Estate",
  "Review",
  "Risk Assessment",
  "SaaS",
  "social",
  "spa",
  "SSO",
  "Stock Market",
  "Underwriting",
  "Video",
  "wellness",
];


export const TeamMembersCardKeywords = [
  {
    keyword: "AI",
    title: "AI In Website Design",
    imgUrl: image,
  },
  {
    keyword: "AI",
    title: "AI In Website Design",
    imgUrl: image,
  },
  {
    keyword: "B2B",
    title: "B2B In Website Design",
    imgUrl: image,
  },
  {
    keyword: "SSO",
    title: "sso In Website Design",
    imgUrl: image,
  }

]